### ISSUE TITLE
hi, nice project! is it stable? how to install? tx!

### ISSUE THREAD

**Issue by peefour** [Itxaka/Gobolino#1]
hi, 
nice project! is it stable? how to install?
 tx!

**Comment by Itxaka** [comment]
Hi there!

It should be stable as it uses docker-py under it which is made but the docker guys.

The install process is pretty easy, I will try to document it in a few hours!

**Comment by peefour** [comment]
ah cool, 
with, stable, I mean if it well tested, and without bugs (production ready)?
I am looking forward to the install instructions!
it should be nice if this program can do most things the docker cli does.

**Comment by Itxaka** [comment]
Hi there,

as you can see there is an install.md rigth now which contains the basic intructions on installing it. I expect to expand it asap.

Regarding the resting and bugs, I haven't done a lot of testing on it yet as it stated as a project to manage my own images and containers, but for the moment I haven't found anything strange or any bugs (yet!).

Regarding the functionality, Im limited by what docker-py can do, but y goal is to have as many functions as I can in the gui :+1: 

Also, Im creating a dockerfile rigth now so the install process is as easy as pulling the image and run it :D

**Comment by peefour** [comment]
Hi,
Thanks!
I still can't find the install instructions??
Are any updates planned?
Maybe you should send this app to docker.io so they can include it in their weekly mailinglist, this will give you more exposure ;)

**Comment by Itxaka** [comment]
Hey,

you got the install instructions at https://github.com/Itxaka/Gobolino/blob/master/INSTALL.md
Update...not a lot. I fixed several things and are planning a small frontface with info about the containers but not too much more, as it does what I wanted it to do.

Any suggestions?

**Comment by peefour** [comment]
Hi
  thanks for your fast answer. ;)
I can't login
What is the default password?
tx

------ Original Message ------

**Comment by Itxaka** [comment]
Did you create the user?

python createuser.py user password

whatever you put on that would be your user and pass.

**Comment by peefour** [comment]
I did "docker run -d itxaka/Gobolino" 
1) But how can I set "python createuser.py user password" in this docker container?

2) can't you provide a default user and password just for testing?
thanks!!

**Comment by peefour** [comment]
I also tried to do a full install (but I prefer using docker container, because I want to keep my host clean), but had lots of troubles

Easy way:

1 - Clone the repository::

git clone https://github.com/Itxaka/Gobolino.git
---> ok
2 - Install dependencies::

pip install -r requirements.txt
--> couldn't find requirements.txt, I searched for it and found it
3 - Edit config.py to add your data, usually you will only need to add a secret key to the config
-->couldn't find config.py, also not after searching
4 - Create a user::

python createuser.py user password
-->python gave error because it could not find  createuser.py 
5 - Execute runserver.py::

python runserver.py
--> I did not get so far, because of problems above
6 - Connect to your server and start managing your docker images and containers!
-->idem

**Comment by Itxaka** [comment]
Yeah, forgot to mention that all the steps after the clone should be done in the web folder.
Can you try it again but do all that stuff on the web folder instead?

**Comment by peefour** [comment]
hi,

can you be more specific? 
-what is the path/name of the folder?
-is it on the host?

tx for your quick reply!!

**Comment by peefour** [comment]
in fact, I just to run the dockerfile to test this out, without installing anything. is that possible?

"I did "docker run -d itxaka/Gobolino"
1) But how can I set "python createuser.py user password" in this docker container?

2) can't you provide a default user and password just for testing?
thanks!!"

**Comment by Itxaka** [comment]
Hey,

If You use the docker container a user is created with user admin and password admin

**Comment by peefour** [comment]
thanks! I can login now

but I get an error:

## any idea what is wrong?

requests.exceptions.ConnectionError

ConnectionError: UnixHTTPConnectionPool(host='localhost', port=None): Max retries exceeded with url: /run/docker.sock/v1.8/info (Caused by <class 'socket.error'>: [Errno 2] No such file or directory)
Traceback (most recent call last)

```
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__

return self.wsgi_app(environ, start_response)

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app

response = self.make_response(self.handle_exception(e))

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception

reraise(exc_type, exc_value, tb)

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app

response = self.full_dispatch_request()

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception

reraise(exc_type, exc_value, tb)

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request

rv = self.dispatch_request()

File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request

return self.view_functions[rule.endpoint](**req.view_args)

File "/var/www/web/views.py", line 33, in index

info = c.info()

File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 532, in info

return self._result(self._get(self._url("/info")),

File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 102, in _get

return self.get(url, **self._set_request_timeout(kwargs))

File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 395, in get

return self.request('GET', url, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 383, in request

resp = self.send(prep, **send_kwargs)

File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 486, in send

r = adapter.send(request, **kwargs)

File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send

raise ConnectionError(e)

ConnectionError: UnixHTTPConnectionPool(host='localhost', port=None): Max retries exceeded with url: /run/docker.sock/v1.8/info (Caused by <class 'socket.error'>: [Errno 2] No such file or directory)
```

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

```
dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
```

Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by peefour** [comment]
Hi,

I installed the container again on a freshly installed ubuntu,

root@test ~ # docker run -d -p 5000:5000 itxaka/gobolino
c30ac0cd176a3e28dbf91f5e7e2c79446c15684c1cb7ec1635bb2040d717c844
root@test ~ #

that goes well, and I get the login screen, but when I put in the credentials admin/admin then I get the same error: see screenshot: http://awesomescreenshot.com/0f62q6jre5

what can be wrong?

**Comment by Itxaka** [comment]
Umm, Ill have a look

**Comment by peefour** [comment]
Thanks!
I love to try gobolino out !!
